//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace BonaStoco.AP1.Web.sercurityws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BonastocoServicesBinding", Namespace="urn:BonastocoServices")]
    public partial class BonastocoServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback helloOperationCompleted;
        
        private System.Threading.SendOrPostCallback logonOperationCompleted;
        
        private System.Threading.SendOrPostCallback changepasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetcompanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback bonastocostatisticOperationCompleted;
        
        private System.Threading.SendOrPostCallback stocktransferOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BonastocoServices() {
            this.Url = global::BonaStoco.AP1.Web.Properties.Settings.Default.BonaStoco_AP1_Web_sercurityws_BonastocoServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event helloCompletedEventHandler helloCompleted;
        
        /// <remarks/>
        public event logonCompletedEventHandler logonCompleted;
        
        /// <remarks/>
        public event changepasswordCompletedEventHandler changepasswordCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        public event resetcompanyCompletedEventHandler resetcompanyCompleted;
        
        /// <remarks/>
        public event bonastocostatisticCompletedEventHandler bonastocostatisticCompleted;
        
        /// <remarks/>
        public event stocktransferCompletedEventHandler stocktransferCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#hello", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverResponse hello(sayHello person) {
            object[] results = this.Invoke("hello", new object[] {
                        person});
            return ((serverResponse)(results[0]));
        }
        
        /// <remarks/>
        public void helloAsync(sayHello person) {
            this.helloAsync(person, null);
        }
        
        /// <remarks/>
        public void helloAsync(sayHello person, object userState) {
            if ((this.helloOperationCompleted == null)) {
                this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
            }
            this.InvokeAsync("hello", new object[] {
                        person}, this.helloOperationCompleted, userState);
        }
        
        private void OnhelloOperationCompleted(object arg) {
            if ((this.helloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#logon", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public loginResponse logon(Person person) {
            object[] results = this.Invoke("logon", new object[] {
                        person});
            return ((loginResponse)(results[0]));
        }
        
        /// <remarks/>
        public void logonAsync(Person person) {
            this.logonAsync(person, null);
        }
        
        /// <remarks/>
        public void logonAsync(Person person, object userState) {
            if ((this.logonOperationCompleted == null)) {
                this.logonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogonOperationCompleted);
            }
            this.InvokeAsync("logon", new object[] {
                        person}, this.logonOperationCompleted, userState);
        }
        
        private void OnlogonOperationCompleted(object arg) {
            if ((this.logonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logonCompleted(this, new logonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#changepassword", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverResponse changepassword(changepasswd person) {
            object[] results = this.Invoke("changepassword", new object[] {
                        person});
            return ((serverResponse)(results[0]));
        }
        
        /// <remarks/>
        public void changepasswordAsync(changepasswd person) {
            this.changepasswordAsync(person, null);
        }
        
        /// <remarks/>
        public void changepasswordAsync(changepasswd person, object userState) {
            if ((this.changepasswordOperationCompleted == null)) {
                this.changepasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangepasswordOperationCompleted);
            }
            this.InvokeAsync("changepassword", new object[] {
                        person}, this.changepasswordOperationCompleted, userState);
        }
        
        private void OnchangepasswordOperationCompleted(object arg) {
            if ((this.changepasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changepasswordCompleted(this, new changepasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#logout", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverResponse logout(logmeout person) {
            object[] results = this.Invoke("logout", new object[] {
                        person});
            return ((serverResponse)(results[0]));
        }
        
        /// <remarks/>
        public void logoutAsync(logmeout person) {
            this.logoutAsync(person, null);
        }
        
        /// <remarks/>
        public void logoutAsync(logmeout person, object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[] {
                        person}, this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new logoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#resetcompany", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverResponse resetcompany(serverToken person) {
            object[] results = this.Invoke("resetcompany", new object[] {
                        person});
            return ((serverResponse)(results[0]));
        }
        
        /// <remarks/>
        public void resetcompanyAsync(serverToken person) {
            this.resetcompanyAsync(person, null);
        }
        
        /// <remarks/>
        public void resetcompanyAsync(serverToken person, object userState) {
            if ((this.resetcompanyOperationCompleted == null)) {
                this.resetcompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetcompanyOperationCompleted);
            }
            this.InvokeAsync("resetcompany", new object[] {
                        person}, this.resetcompanyOperationCompleted, userState);
        }
        
        private void OnresetcompanyOperationCompleted(object arg) {
            if ((this.resetcompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetcompanyCompleted(this, new resetcompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#bonastocostatistic", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverStatistic bonastocostatistic(serverToken person) {
            object[] results = this.Invoke("bonastocostatistic", new object[] {
                        person});
            return ((serverStatistic)(results[0]));
        }
        
        /// <remarks/>
        public void bonastocostatisticAsync(serverToken person) {
            this.bonastocostatisticAsync(person, null);
        }
        
        /// <remarks/>
        public void bonastocostatisticAsync(serverToken person, object userState) {
            if ((this.bonastocostatisticOperationCompleted == null)) {
                this.bonastocostatisticOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbonastocostatisticOperationCompleted);
            }
            this.InvokeAsync("bonastocostatistic", new object[] {
                        person}, this.bonastocostatisticOperationCompleted, userState);
        }
        
        private void OnbonastocostatisticOperationCompleted(object arg) {
            if ((this.bonastocostatisticCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bonastocostatisticCompleted(this, new bonastocostatisticCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BonastocoServices#stocktransfer", RequestNamespace="urn:BonastocoServices", ResponseNamespace="urn:BonastocoServices")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public serverResponse stocktransfer(stockTransfer person) {
            object[] results = this.Invoke("stocktransfer", new object[] {
                        person});
            return ((serverResponse)(results[0]));
        }
        
        /// <remarks/>
        public void stocktransferAsync(stockTransfer person) {
            this.stocktransferAsync(person, null);
        }
        
        /// <remarks/>
        public void stocktransferAsync(stockTransfer person, object userState) {
            if ((this.stocktransferOperationCompleted == null)) {
                this.stocktransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstocktransferOperationCompleted);
            }
            this.InvokeAsync("stocktransfer", new object[] {
                        person}, this.stocktransferOperationCompleted, userState);
        }
        
        private void OnstocktransferOperationCompleted(object arg) {
            if ((this.stocktransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stocktransferCompleted(this, new stocktransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class sayHello {
        
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class stockTransfer {
        
        private string tokenField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class serverStatistic {
        
        private string tokenField;
        
        private int statusField;
        
        private string messageField;
        
        private int trialField;
        
        private int freeField;
        
        private int cobrandingField;
        
        private int personalField;
        
        private int corporateField;
        
        private int productField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int trial {
            get {
                return this.trialField;
            }
            set {
                this.trialField = value;
            }
        }
        
        /// <remarks/>
        public int free {
            get {
                return this.freeField;
            }
            set {
                this.freeField = value;
            }
        }
        
        /// <remarks/>
        public int cobranding {
            get {
                return this.cobrandingField;
            }
            set {
                this.cobrandingField = value;
            }
        }
        
        /// <remarks/>
        public int personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
            }
        }
        
        /// <remarks/>
        public int corporate {
            get {
                return this.corporateField;
            }
            set {
                this.corporateField = value;
            }
        }
        
        /// <remarks/>
        public int product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class serverToken {
        
        private string tokenField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class logmeout {
        
        private string tokenField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class changepasswd {
        
        private string tokenField;
        
        private string oldpasswordField;
        
        private string newpasswordField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string oldpassword {
            get {
                return this.oldpasswordField;
            }
            set {
                this.oldpasswordField = value;
            }
        }
        
        /// <remarks/>
        public string newpassword {
            get {
                return this.newpasswordField;
            }
            set {
                this.newpasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class loginResponse {
        
        private string tokenField;
        
        private int statusField;
        
        private string messageField;
        
        private int roleField;
        
        private int companyidField;
        
        private string companyField;
        
        private int refreshField;
        
        private int usertypeField;
        
        private int limitField;
        
        private System.DateTime expiredField;
        
        private string headofficeField;
        
        private int reselleridField;
        
        private string reselleremailField;
        
        private string reservedField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int companyid {
            get {
                return this.companyidField;
            }
            set {
                this.companyidField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public int refresh {
            get {
                return this.refreshField;
            }
            set {
                this.refreshField = value;
            }
        }
        
        /// <remarks/>
        public int usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
            }
        }
        
        /// <remarks/>
        public int limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime expired {
            get {
                return this.expiredField;
            }
            set {
                this.expiredField = value;
            }
        }
        
        /// <remarks/>
        public string headoffice {
            get {
                return this.headofficeField;
            }
            set {
                this.headofficeField = value;
            }
        }
        
        /// <remarks/>
        public int resellerid {
            get {
                return this.reselleridField;
            }
            set {
                this.reselleridField = value;
            }
        }
        
        /// <remarks/>
        public string reselleremail {
            get {
                return this.reselleremailField;
            }
            set {
                this.reselleremailField = value;
            }
        }
        
        /// <remarks/>
        public string reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class Person {
        
        private string emailField;
        
        private string passwordField;
        
        private string codeField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BonastocoServices")]
    public partial class serverResponse {
        
        private string tokenField;
        
        private int statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void logonCompletedEventHandler(object sender, logonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public loginResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((loginResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void changepasswordCompletedEventHandler(object sender, changepasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changepasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changepasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void logoutCompletedEventHandler(object sender, logoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void resetcompanyCompletedEventHandler(object sender, resetcompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetcompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetcompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bonastocostatisticCompletedEventHandler(object sender, bonastocostatisticCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bonastocostatisticCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bonastocostatisticCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverStatistic Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverStatistic)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void stocktransferCompletedEventHandler(object sender, stocktransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stocktransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stocktransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serverResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serverResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591